before_script:
    - pip install -U setuptools
    - pip install Cython
    - pip install --upgrade -e .[test]

.before_script_alpine: &before_alpine
    before_script:
        - apk add --no-cache openssl gcc musl-dev
        - pip install Cython setuptools
        - pip install --upgrade -e .[test]

.test_template: &test
    script:
        - python setup.py test

python 2.7alpine:
    image: python:2.7-alpine
    <<: *before_alpine
    <<: *test

python 3.3alpine:
    image: python:3.3-alpine
    <<: *before_alpine
    <<: *test

python 3.4alpine:
    image: python:3.4-alpine
    <<: *before_alpine
    <<: *test

python 3.5alpine:
    image: python:3.5-alpine
    <<: *before_alpine
    <<: *test

python 3.6alpine:
    image: python:3.6-alpine
    <<: *before_alpine
    <<: *test

python pypy:
    image: pypy:2
    <<: *test

python pypy3:
    image: pypy:3
    <<: *test
